apiVersion: opsworks.aws.upbound.io/v1beta2
kind: CustomLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/customlayer
  labels:
    testing.upbound.io/example-name: custlayer
  name: custlayer
spec:
  forProvider:
    name: My Awesome Custom Layer
    shortName: awesome
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
