apiVersion: opsworks.aws.upbound.io/v1beta2
kind: HAProxyLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/haproxylayer
  labels:
    testing.upbound.io/example-name: lb
  name: lb
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    statsPassword: foobarbaz
