apiVersion: opsworks.aws.upbound.io/v1beta2
kind: MemcachedLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/memcachedlayer
  labels:
    testing.upbound.io/example-name: cache
  name: cache
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
