apiVersion: opsworks.aws.upbound.io/v1beta2
kind: MySQLLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/mysqllayer
  labels:
    testing.upbound.io/example-name: db
  name: db
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
