apiVersion: opsworks.aws.upbound.io/v1beta2
kind: NodeJSAppLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/nodejsapplayer
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
