apiVersion: opsworks.aws.upbound.io/v1beta2
kind: StaticWebLayer
metadata:
  annotations:
    meta.upbound.io/example-id: opsworks/v1beta2/staticweblayer
  labels:
    testing.upbound.io/example-name: web
  name: web
spec:
  forProvider:
    stackIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
