//go:build (cloudsearch || config || all) && !ignore_autogenerated

package cloudsearch

import (
	"github.com/crossplane/upjet/pkg/config"

	pconfig "github.com/upbound/provider-aws/config"
)

// Configure adds configurations for the cloudsearch group.
func Configure(p *config.Provider) {
	p.AddResourceConfigurator("aws_cloudsearch_domain", func(r *config.Resource) {
		r.UseAsync = true
	})

	p.AddResourceConfigurator("aws_cloudsearch_domain_service_access_policy", func(r *config.Resource) {
		r.UseAsync = true
	})
}

func init() {
	pconfig.ProviderConfiguration.AddConfig(Configure)
}
