# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: globalaccelerator.aws.upbound.io/v1beta2
kind: Accelerator
metadata:
  annotations:
    meta.upbound.io/example-id: globalaccelerator/v1beta2/accelerator
  name: sample-accelerator
spec:
  forProvider:
    ipAddressType: IPV4
    name: sample-accelerator
    region: eu-west-1
  writeConnectionSecretToRef:
    name: accelerator
    namespace: upbound-system
