apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: example
  labels:
    testing.upbound.io/example-name: secretsmanager
spec:
  forProvider:
    name: example-${Rand.RFC1123Subdomain}
    region: us-west-1
