apiVersion: lambda.aws.upbound.io/v1beta2
kind: FunctionURL
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta2/functionurl
  labels:
    testing.upbound.io/example-name: test_latest
  name: test-latest
spec:
  forProvider:
    authorizationType: NONE
    functionNameSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    region: us-west-1
