//go:build (rolesanywhere || config || all) && !ignore_autogenerated

package rolesanywhere

import (
	"github.com/crossplane/upjet/pkg/config"

	pconfig "github.com/upbound/provider-aws/config"
	"github.com/upbound/provider-aws/config/common"
)

// Configure adds configurations for the rolesanywhere group.
func Configure(p *config.Provider) {
	p.AddResourceConfigurator("aws_rolesanywhere_profile", func(r *config.Resource) {
		r.References["role_arns"] = config.Reference{
			Type:      "github.com/upbound/provider-aws/apis/iam/v1beta1.Role",
			Extractor: common.PathARNExtractor,
		}
	})
}

func init() {
	pconfig.ProviderConfiguration.AddConfig(Configure)
}
