# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticache.aws.upbound.io/v1beta2
kind: ReplicationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: elasticache/v1beta2/replicationgroup
    uptest.upbound.io/timeout: "3600"
  labels:
    testing.upbound.io/example-name: example
  name: example-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    automaticFailoverEnabled: true
    description: example description
    maintenanceWindow: sun:05:00-sun:09:00
    nodeType: cache.m4.large
    numCacheClusters: 2
    parameterGroupName: default.redis7
    port: 6379
    preferredCacheClusterAzs:
      - us-west-1a
      - us-west-1b
    region: us-west-1
