apiVersion: networkmanager.aws.upbound.io/v1beta2
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: networkmanager/v1beta2/device
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    globalNetworkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    siteIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
