apiVersion: waf.aws.upbound.io/v1beta2
kind: SQLInjectionMatchSet
metadata:
  annotations:
    meta.upbound.io/example-id: waf/v1beta2/sqlinjectionmatchset
  labels:
    testing.upbound.io/example-name: sql_injection_match_set
  name: sql-injection-match-set
spec:
  forProvider:
    name: tf-sql_injection_match_set
    region: us-west-1
    sqlInjectionMatchTuples:
    - fieldToMatch:
      - type: QUERY_STRING
      textTransformation: URL_DECODE
