#!/usr/bin/env bash

# HO.

TAGGER="/tmp/buildtagger"
REPO_ROOT="/Users/alper/data/workspaces/github.com/ulucinar/upbound/provider-aws"
DELETE_TAGS="--delete"

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/.+\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/zz_groupversion_info\.go" --tag-format "(%s || register || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "zz_(register)\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode file ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "(.+)/.+/zz_controller\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "zz_(.+)_setup\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode file ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/cmd/provider --regex "(.+)/zz_main\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/config --regex "(.+)/config\.go" --tag-format "(%s || config || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

# cmd/generator/main.go                               -> //go:build config || generate || all
# config/autoscaling/config_test.go                   -> //go:build (autoscaling || config || all) && !ignore_autogenerated
# config/common/apis/lambda/extractor.go              -> //go:build config || lambda || all
# config/config_registry.go (new file)                -> //go:build register || config || all
# config/overrides.go                                 -> //go:build register || config || all
# config/provider.go                                  -> //go:build register || config || all
# internal/controller/eks/clusterauth/controller.go   -> //go:build eks || all
