#!/usr/bin/env bash

# HO.

TAGGER="/tmp/buildtagger"
REPO_ROOT="/Users/alper/data/workspaces/github.com/ulucinar/upbound/provider-aws"
DELETE_TAGS=""

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/.+\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis --regex "(.+)/.+/zz_groupversion_info\.go" --tag-format "(%s || register || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "(.+)/.+/zz_controller\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller --regex "zz_(.+)_setup\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode file ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/cmd/provider --regex "(.+)/zz_main\.go" --tag-format "(%s || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

"${TAGGER}" --parent-dir "${REPO_ROOT}"/config --regex "(.+)/config\.go" --tag-format "(%s || config || all) && !ignore_autogenerated" --mode dir ${DELETE_TAGS}

# constant tags
# apis/zz_register.go -> (apiregister || register || all) && !ignore_autogenerated
"${TAGGER}" --parent-dir "${REPO_ROOT}"/apis/zz_register.go --tag-format "(apiregister || register || all) && !ignore_autogenerated" --mode file ${DELETE_TAGS}
# cmd/generator/main.go -> config || generate || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/cmd/generator/main.go --tag-format "config || generate || all" --mode file ${DELETE_TAGS}
# config/autoscaling/config_test.go -> (autoscaling || config || all) && !ignore_autogenerated
"${TAGGER}" --parent-dir "${REPO_ROOT}"/config/autoscaling/config_test.go --tag-format "(autoscaling || config || all) && !ignore_autogenerated" --mode file ${DELETE_TAGS}
# config/common/apis/lambda/extractor.go -> config || lambda || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/config/common/apis/lambda/extractor.go --tag-format "config || lambda || all" --mode file ${DELETE_TAGS}
# config/config_registry.go -> configregistry || register || config || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/config/config_registry.go --tag-format "configregistry || register || config || all" --mode file ${DELETE_TAGS}
# config/overrides.go -> configprovider || register || config || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/config/overrides.go --tag-format "configprovider || register || config || all" --mode file ${DELETE_TAGS}
# config/provider.go -> configprovider || register || config || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/config/provider.go --tag-format "configprovider || register || config || all" --mode file ${DELETE_TAGS}
# internal/controller/eks/clusterauth/controller.go -> eks || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller/eks/clusterauth/controller.go --tag-format "eks || all" --mode file ${DELETE_TAGS}
# internal/controller/eks/clusterauth/eks.go -> eks || all
"${TAGGER}" --parent-dir "${REPO_ROOT}"/internal/controller/eks/clusterauth/eks.go --tag-format "eks || all" --mode file ${DELETE_TAGS}