//go:build (cloudformation || config || all) && !ignore_autogenerated

/*
Copyright 2024 Upbound Inc.
*/

package cloudformation

import (
	"github.com/crossplane/upjet/pkg/config"

	pconfig "github.com/upbound/provider-aws/config"
)

// Configure adds configurations for the cloudformation group.
func Configure(p *config.Provider) {
	p.AddResourceConfigurator("aws_cloudformation_stack_set_instance", func(r *config.Resource) {
		r.TerraformConfigurationInjector = func(jsonMap map[string]any, params map[string]any) error {
			params["region"] = jsonMap["region"]
			return nil
		}
	})
}

func init() {
	pconfig.ProviderConfiguration.AddConfig(Configure)
}
