apiVersion: iam.aws.upbound.io/v1beta1
kind: OpenIDConnectProvider
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "This resource needs valid OpenID Connect id and url."
  name: example
spec:
  forProvider:
    clientIdList:
    - <clientID>
    thumbprintList:
    - <thumbprint>
    url: https://accounts.google.com
  providerConfigRef:
    name: example