apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterActivityStream
metadata:
  name: default
  annotations:
    upjet.upbound.io/manual-intervention: "This resource has a reference to Cluster, which needs manual intervention."
spec:
  forProvider:
    kmsKeyIdRef:
      name: default
    mode: async
    region: us-west-1
    resourceArnRef:
      name: example
---

apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  name: default
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of ClusterActivityStream, which needs manual intervention."
spec:
  forProvider:
    description: AWS KMS Key to encrypt Database Activity Stream
    region: us-west-1

