apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/clustersnapshot
    upjet.upbound.io/manual-intervention: "This resource has a reference to Cluster, which needs manual intervention."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbClusterIdentifier: database-1
    dbClusterSnapshotIdentifier: resourcetestsnapshot1234
    region: us-west-1