apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: sample-s3-policy
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of ClusterRoleAssociation, which needs manual intervention."
spec:
  forProvider:
    name: sample-s3-policy
    policy: |
      {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:*",
                "s3-object-lambda:*"
              ],
              "Resource": "*"
            }
          ]
      }

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: sample-db-role
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of ClusterRoleAssociation, which needs manual intervention."
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
              "Service": "rds.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: sample-role-attach
  annotations:
    upjet.upbound.io/manual-intervention: "This resource is a dependency of ClusterRoleAssociation, which needs manual intervention."
spec:
  forProvider:
    policyArnRef:
      name: sample-s3-policy
    roleRef:
      name: sample-db-role

---

apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterRoleAssociation
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "This resource has a reference to Cluster, which needs manual intervention."
spec:
  forProvider:
    region: us-west-1
    dbClusterIdentifierRef:
      name: example
    featureName: s3Import
    roleArnRef:
      name: sample-db-role
