apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterParameterGroup
metadata:
  name: example
spec:
  forProvider:
    region: us-west-1
    description: RDS default cluster parameter group
    family: aurora5.6
    parameter:
      - name: character_set_server
        value: utf8
      - name: character_set_client
        value: utf8