apiVersion: rds.aws.upbound.io/v1beta1
kind: DBInstanceAutomatedBackupsReplication
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbinstanceautomatedbackupsreplication
    upjet.upbound.io/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: us-east-2
    retentionPeriod: 7
    sourceDbInstanceArn: arn-for-db-instance