apiVersion: rds.aws.upbound.io/v1beta1
kind: DBSnapshotCopy
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbsnapshotcopy
    upjet.upbound.io/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    sourceDbSnapshotIdentifierSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    targetDbSnapshotIdentifier: testsnapshot1234-copy
---
apiVersion: rds.aws.upbound.io/v1beta1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta1/dbsnapshotcopy
    upjet.upbound.io/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dbInstanceIdentifier: database-1
    region: us-west-1