apiVersion: rds.aws.upbound.io/v1beta1
kind: InstanceRoleAssociation
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
spec:
  forProvider:
    dbInstanceIdentifierRef:
      name: example-dbinstance
    featureName: s3Import
    region: us-west-1
    roleArnRef:
      name: sample-db-role
