apiVersion: rds.aws.upbound.io/v1beta1
kind: Snapshot
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "This resource has a reference to Instance, which needs manual intervention."
spec:
  forProvider:
    region: us-west-1
    dbInstanceIdentifierRef:
      name: example-dbinstance
