apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: example
spec:
  forProvider:
    region: us-west-1
    cidrBlocks:
      - 10.0.0.0/16
    fromPort: 0
    protocol: tcp
    securityGroupIdRef:
      name: example
    toPort: 65535
    type: ingress