//go:build (ecrpublic || config || all) && !ignore_autogenerated

/*
Copyright 2021 Upbound Inc.
*/

package ecrpublic

import (
	"github.com/crossplane/upjet/pkg/config"

	pconfig "github.com/upbound/provider-aws/config"
)

// Configure adds configurations for the ecrpublic group.
func Configure(p *config.Provider) {
	p.AddResourceConfigurator("aws_ecrpublic_repository", func(r *config.Resource) {
		// Deletion takes a while.
		r.UseAsync = true
	})
}

func init() {
	pconfig.ProviderConfiguration.AddConfig(Configure)
}
