name: Native Version Bump

on:
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.19'

jobs:
  bump-version-makefile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "cache=$(make go.cachedir)" >> $GITHUB_OUTPUT

      - name: Cache the Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go.outputs.cache }}
          key: ${{ runner.os }}-build-lint-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-lint-

      - name: Cache Go Dependencies
        uses: actions/cache@v3
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Vendor Dependencies
        run: make vendor vendor.check

      - name: Bump native provider version in Makefile
        id: bump-mk
        run: |
          sed -i -E "s/^(export[[:space:]]+TERRAFORM_PROVIDER_VERSION[[:space:]]*:=[[:space:]]*).+/\1$(curl -sL 'https://registry.terraform.io/v1/providers/hashicorp/aws' | jq -r .version)/" Makefile
          echo "bumped=$(git diff --name-only Makefile)" >> $GITHUB_OUTPUT
          echo "version=$(curl -sL 'https://registry.terraform.io/v1/providers/hashicorp/aws' | jq -r .version)" >> $GITHUB_OUTPUT

      - name: Install goimports & run make generate
        if: steps.bump-mk.outputs.bumped != ''
        run: |
          go install golang.org/x/tools/cmd/goimports
          make generate

      - name: New pull request
        if: steps.bump-mk.outputs.bumped != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: Bump native provider to version ${{ steps.bump-mk.outputs.version }}
          commit-message: Bump native provider to version ${{ steps.bump-mk.outputs.version }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          labels: |
            automated
