name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: ulucinar/uptest/.github/workflows/pr-comment-trigger.yml@ci-disk-cleanup
    with:
      go-version: 1.21
    secrets:
      UPTEST_CLOUD_CREDENTIALS: ${{ secrets.UPTEST_CLOUD_CREDENTIALS }}
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
